### ISSUE TITLE
Create a when to meet poll for students

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme134#10]
it would be nice to get some data on when students are commonly available each week to help organize the labs and office hours. We should poll them for 1 hours 8am to 8pm M-F.

@earasteh Can you set up a when2meet poll? We will send it out after the first day of class.

**Comment by earasteh** [comment]
Here is the poll:
http://whenisgood.net/qse22ip

**Comment by moorepants** [comment]
@earasteh I was just thinking that actually we shouldn't block off any slots except for the actual class period, because I may be able to have my office hours at a time that you can't. Can you adjust it so we have 9 to 8 M-F except 11-12 MWF? Sorry about that.
